### ISSUE TITLE
SSE Support

### ISSUE THREAD

**Issue by StrangeZak** [StrangeZak/Handmade-Math#15]
Add SSE support for all Vector, and Matrix Operations

**Comment by bvisness** [comment]
This is done...?

**Comment by StrangeZak** [comment]
Nope. Vectors and Mat4s do not have any SSE yet.

**Comment by DanielGibson** [comment]
The code doesn't build without SSE currently, because HMM_RSquareRootF() uses HMM_SqrtF() instead of HMM_SquareRootF().

Furthermore I think it's not a good idea that SSE is used by default everywhere, because then the user has to `#define HANDMADE_MATH_NO_SSE` if there's no SSE available (e.g. i686 build or ARM or whatever).
Maybe add 
```c
#ifndef __SSE__
#define HANDMADE_MATH_NO_SSE
#endif
```
somewhere at the top?
I think `HANDMADE_MATH_NO_SSE` only makes sense for disabling SSE if it **is** available.

**Comment by StrangeZak** [comment]
Ill take a look at this and fix this in the coming days.

**Comment by DanielGibson** [comment]
Thanks a lot!

**Comment by StrangeZak** [comment]
@DanielGibson Fixing this tonight sorry life has been so busy

**Comment by StrangeZak** [comment]
I'd say we take advantage of a lot of SSE features now. Will close this for the time being.
