### ISSUE TITLE
HMM_Power does not support fractional exponents

### ISSUE THREAD

**Issue by bvisness** [StrangeZak/Handmade-Math#29]
The function signature for `HMM_Power` is currently `HMM_Power(float Base, int Exponent)`. Because `Exponent` is an `int`, it is not possible to use fractional exponents at all.

This would add to the complexity of the function, so it would perhaps be wise to add an `HMM_PowerF` or something to preserve performance for the (probably more common) integer exponent case.

**Comment by StrangeZak** [comment]
My friend Miblo, is actually working on a new quick power function. I will inform him on this so when he writes the new power function he can squash these requests also

**Comment by miblodelcarpio** [comment]
Cheers chaps, I (or, rather, @mmozeiko) have accelerated the regular `HMM_Power()` and I'll next learn how to handle floating point exponents for a new `HMM_PowerF()`.

**Comment by mmozeiko** [comment]
This is pretty easy. For x and y floats, pow(x, y) is exp(y*ln(x)).

    HMM_Power(float Base, float Exponent)
    {
        return expf(Exponent * logf(Base));
    }

Obviously this will work only when Base > 0.

There are probably a bit faster variants, like exp2(y*log2(x)), because log2 should be faster operation than natural logarithm on floats. But this needs to be verified, not sure how faster it is nowadays.

**Comment by bvisness** [comment]
Fixed in #40
